function Abs (Value);
function ACos (Angle);
function ActivateGadget (#Gadget);
function ActivateWindow ();
function Add3DArchive (Name$, Type);
function AddBillboard (#Billboard, #BillboardGroup, x, y, z);
function AddDate (Date, Field, Offset);
function AddElement (LinkedList());
function AddGadgetColumn (#Gadget, Position, Title$, Width);
function AddGadgetItem (#Gadget, Position, Text$ [, ImageID]);
function AddKeyboardShortcut (#Window, Key, MenuItemID);
function AddMaterialLayer (#Material, TextureID [, Mode]);
function AddPackFile (Filename$ [, Level]);
function AddPackMemory (MemoryID, Size [, Level]);
function AddStatusBarField (Width);
function AddSysTrayIcon (#SysTrayIcon, WindowID, ImageID);
function AdvancedGadgetEvents (Flag);
function AllocateMemory (#Memory, Size [, Flags]);
function AmbientColor (Color);
function AnimateEntity (#Entity, AnimationName$);
function Asc (String);
function ASin (Angle);
function ATan (Angle);
function AvailableScreenMemory ();
function BackColor (Red, Green, Blue);
function Base64Encoder (InputBuffer, InputLength, OutputBuffer, OutputLength);
function BillboardGroupLocate (#BillboardGroup, x, y, z);
function BillboardGroupMaterial (#BillboardGroup, MaterialID);
function BillboardGroupX (#BillboardGroup);
function BillboardGroupY (#BillboardGroup);
function BillboardGroupZ (#BillboardGroup);
function BillboardHeight (#Billboard, #BillboardGroup);
function BillboardLocate (#Billboard, #BillboardGroup, x, y, z);
function BillboardWidth (#Billboard, #BillboardGroup);
function BillboardX (#Billboard, #BillboardGroup);
function BillboardY (#Billboard, #BillboardGroup);
function BillboardZ (#Billboard, #BillboardGroup);
function Bin (Number);
function Blue (Color);
function Box (x, y, Width, Height [, Color]);
function ButtonGadget (#Gadget, x, y, Width, Height, Text$ [, Flags]);
function ButtonImageGadget (#Gadget, x, y, Width, Heigth, ImageID);
function CallCFunction (#Library, FunctionName$, [Arg1, [Arg2, ...]]);
function CallCFunctionFast (*Function, [Arg1, [Arg2, ...]]);
function CallFunction (#Library, FunctionName$, [Arg1, [Arg2, ...]]);
function CallFunctionFast (*Function, [Arg1, [Arg2, ...]]);
function CameraBackColor (#Camera, Color);
function CameraFOV (#Camera, FOV);
function CameraLocate (#Camera, x, y, z);
function CameraLookAt (#Camera, x, y, z);
function CameraProjection (#Camera, Mode);
function CameraRange (#Camera, Near, Far);
function CameraRenderMode (#Camera, RenderMode);
function CameraX (#Camera);
function CameraY (#Camera);
function CameraZ (#Camera);
function CatchImage (#Image, *Memory);
function CatchSound (#Sound, MemoryAddress [, Length]);
function CatchSprite (#Sprite, MemoryID [, Mode]);
function CDAudioLength ();
function CDAudioName ();
function CDAudioStatus ();
function CDAudioTrackLength (TrackNumber);
function CDAudioTracks ();
function CDAudioTrackSeconds ();
function ChangeAlphaIntensity (R, G, B);
function ChangeCurrentElement (linkedlist(), *NewElement);
function ChangeGamma (R, G, B, Flags);
function ChangeListIconGadgetDisplay (#ListIconGadget, Mode);
function ChangeSysTrayIcon (#SysTrayIcon, ImageID);
function CheckBoxGadget (#Gadget, x, y, Width, Height, Text$ [, Flags]);
function Chr (ASCII);
function Circle (x, y, Radius [, Color]);
function ClearBillboards (#BillboardGroup);
function ClearClipboard ();
function ClearConsole ();
function ClearError ();
function ClearGadgetItemList (#Gadget);
function ClearList (LinkedList());
function ClearScreen (R, G, B);
function ClipSprite (#Sprite, x, y, Width, Height);
function CloseConsole ();
function CloseDatabase (#Database);
function CloseFile (#File);
function CloseFont (#Font);
function CloseGadgetList ();
function CloseHelp ();
function CloseLibrary (#Library);
function CloseNetworkConnection (ConnectionID);
function CloseNetworkServer ();
function ClosePack ();
function ClosePreferences ();
function CloseScreen ();
function CloseSubMenu ();
function CloseTreeGadgetNode (#Gadget [, Position]);
function CloseWindow (#Window);
function ColorRequester ();
function ComboBoxGadget (#Gadget, x, y, Width, Heigth [, Flags]);
function CompareMemory (SourceMemoryID, DestinationMemoryID, Length);
function CompareMemoryString (String1$, String2$ [, Mode [, Length]]);
function ConsoleColor (CharacterColor, BackgroundColor);
function ConsoleCursor (Height);
function ConsoleLocate (x, y);
function ConsoleTitle (Title$);
function ContainerGadget (#Gadget, x, y, Width, Heigth, [, Flags]);
function CopyDirectory (SourceDirectory$, DestinationDirectory$, Pattern$ [, Flags]);
function CopyEntity (#Entity, #NewEntity);
function CopyFile (SourceFileName$, DestinationFileName$);
function CopyImage (#Image1, #Image2);
function CopyLight (#Light, #NewLight);
function CopyMaterial (#Material, #NewMaterial);
function CopyMemory (SourceMemoryID, DestinationMemoryID, Length);
function CopyMemoryString (String$ [, DestinationMemoryID]);
function CopyMesh (#Mesh, #NewMesh);
function CopySprite (#Sprite1, #Sprite2 [, Mode]);
function CopyTexture (#Texture, #NewTexture);
function Cos (Angle);
function CountBillboards (#BillboardGroup);
function CountGadgetItems (#Gadget);
function CountLibraryFunctions (#Library);
function CountList (LinkedList());
function CountMaterialLayers (#Material);
function CountRenderedTriangles ();
function CountTreeGadgetNodeItems (#Gadget, Item);
function CRC32Fingerprint (Buffer, Length);
function CreateBillboardGroup (#BillboardGroup, MaterialID, DefaultBillboardWidth, DefaultBillboardHeight, [x, y, z]);
function CreateCamera (#Camera, x, y, Width, Height);
function CreateDirectory (DirectoryName$);
function CreateEntity (#Entity, MeshID, MaterialID, [, x, y, z]);
function CreateFile (#File, FileName$);
function CreateGadgetList (WindowID());
function CreateImage (#Image, Width, Height);
function CreateLight (#Light, Color [, x, y, z]);
function CreateMaterial (#Material, TextureID);
function CreateMenu (#Menu, WindowID);
function CreateMesh (#Mesh);
function CreateNetworkServer (Port);
function CreatePack (Filename$);
function CreatePalette (#Palette);
function CreateParticleEmitter (#ParticleEmitter, Width, Height, Depth, Type, [, x, y, z]);
function CreatePopupMenu (#Menu);
function CreatePreferences (Filename$);
function CreateSprite (#Sprite1, Width, Height [, Mode]);
function CreateSprite3D (#Sprite3D, #Sprite);
function CreateStatusBar (#StatusBar, WindowID);
function CreateTerrain (Terrain$, MaterialID, [ScaleX, ScaleY, ScaleZ, [Precision]]);
function CreateTexture (#Texture, Width, Height);
function CreateThread (@Procedure(), Parameter);
function CreateToolBar (#ToolBar, WindowID);
function DatabaseColumnName (Column);
function DatabaseColumns ();
function DatabaseColumnType (Column);
function DatabaseDriverDescription ();
function DatabaseDriverName ();
function DatabaseQuery (Request$);
function Date ([Year, Month, Day, Hour, Minute, Second]);
function Day (Date);
function DayOfWeek (Date);
function DayOfYear (Date);
function DefaultPrinter ();
function Delay (Time);
function DeleteDirectory (SourceDirectory$, Pattern$ [, Flags]);
function DeleteElement (LinkedList());
function DeleteFile (FileName$);
function DESFingerprint (Password$, Key$);
function DetachMenu ();
function DirectoryEntryAttributes ();
function DirectoryEntryName ();
function DirectoryEntrySize ();
function DisableGadget (#Gadget, State);
function DisableMaterialLighting (#Material, Disable);
function DisableMenuItem (MenuItem, State);
function DisableToolBarButton (#ButtonID, State);
function DisASMCommand (Address);
function DisplayAlphaSprite (#Sprite, x, y);
function DisplayPalette (#Palette);
function DisplayPopupMenu (#Menu, WindowID() [, x, y]);
function DisplayRGBFilter (x, y, Width, Height, R, G, B);
function DisplayShadowSprite (#Sprite, x, y);
function DisplaySolidSprite (#Sprite, x, y, R, G, B);
function DisplaySprite (#Sprite, x, y);
function DisplaySprite3D (#Sprite3D, x, y [Transparency]);
function DisplayTranslucideSprite (#Sprite, x, y, Intensity);
function DisplayTransparentSprite (#Sprite, x, y);
function DrawImage (ImageID, x, y [, Width, Height]);
function DrawingBuffer ();
function DrawingBufferPitch ();
function DrawingBufferPixelFormat ();
function DrawingFont (FontID());
function DrawingMode (Mode);
function DrawText (Text$);
function EditorGadget (#Gadget, x, y, Width, Heigth [, Flags]);
function EjectCDAudio (State);
function Ellipse (x, y, RadiusX, RadiusY [, Color]);
function Engine3DFrameRate (Type);
function EntityAnimationLength (#Entity);
function EntityLocate (#Entity, x, y, z);
function EntityMaterial (#Entity, MaterialID);
function EntityMesh (#Entity, MeshID);
function EntityX (#Entity);
function EntityY (#Entity);
function EntityZ (#Entity);
function Eof (#File);
function EventGadgetID ();
function EventlParam ();
function EventMenuID ();
function EventType ();
function EventWindowID ();
function EventwParam ();
function ExamineDatabaseDrivers ();
function ExamineDirectory (#Directory, DirectoryName$, Pattern$);
function ExamineIPAddresses ();
function ExamineJoystick ();
function ExamineKeyboard ();
function ExamineLibraryFunctions (#Library);
function ExamineMouse ();
function ExamineScreenModes ();
function ExplorerComboGadget (#Gadget, x, y, Width, Height, Directory$ [, Flags]);
function ExplorerListGadget (#Gadget, x, y, Width, Height, Directory$ [, Flags]);
function ExplorerTreeGadget (#Gadget, x, y, Width, Height, Directory$ [, Flags]);
function FileSeek (NewPosition);
function FileSize (FileName$);
function FillArea (x, y, OutlineColor [, FillColor]);
function FindString (String,StringToFind$, StartPosition);
function FirstDatabaseRow ();
function FirstElement (LinkedList());
function FlipBuffers ();
function Fog (Color, Intensity, StartDistance, EndDistance);
function FontID ();
function FontRequester (FontName$, FontSize, Flags);
function FormatDate (Mask$, Date);
function Frame3DGadget (#Gadget, x, y, Width, Heigth, Text$ [, Flags]);
function FreeBillboardGroup (#BillboardGroup);
function FreeCamera (#Camera);
function FreeEntity (#Entity);
function FreeGadget (#Gadget);
function FreeImage (#Image);
function FreeLight (#Light);
function FreeMaterial (#Material);
function FreeMemory (#Memory);
function FreeMenu (#Menu);
function FreeMesh (#Mesh);
function FreeModule (#Module);
function FreeMovie (#Movie);
function FreePalette (#Palette);
function FreeParticleEmitter (#ParticleEmitter);
function FreeSound (#Sound);
function FreeSprite (#Sprite);
function FreeSprite3D (#Sprite);
function FreeStatusBar (#StatusBar);
function FreeTexture (#Texture);
function FreeToolBar (#ToolBar);
function FrontColor (Red, Green, Blue);
function GadgetHeight (#Gadget);
function GadgetID (#Gadget);
function GadgetItemID (#Gadget, Item);
function GadgetToolTip (#Gadget, Text$);
function GadgetWidth (#Gadget);
function GadgetX (#Gadget);
function GadgetY (#Gadget);
function GetClipboardData (Type);
function GetClipboardText ();
function GetCurrentEIP (Count of skipping ASM;
function GetDatabaseFloat (Column);
function GetDatabaseLong (Column);
function GetDatabaseString (Column);
function GetDisASMString ();
function GetEntityAnimationTime (#Entity);
function GetErrorAddress ();
function GetErrorCounter ();
function GetErrorDescription ();
function GetErrorDLL ();
function GetErrorLineNR ();
function GetErrorModuleName ();
function GetErrorNumber ();
function GetErrorRegister (Offset);
function GetExtensionPart (FullPathName$);
function GetFilePart (FullPathName$);
function GetGadgetItemState (#Gadget, Position);
function GetGadgetItemText (#Gadget, Position, Column);
function GetGadgetState (#Gadget);
function GetGadgetText (#Gadget);
function GetMenuItemState (#Menu, MenuItem);
function GetModulePosition ();
function GetModuleRow ();
function GetPaletteColor (Index);
function GetPathPart (FullPathName$);
function GoToEIP (Address);
function GrabImage (#Image1, #Image2, x, y, Width, Height);
function GrabSprite (#Sprite, x, y, Width, Height [, Mode]);
function Green (Color);
function Hex (Value);
function HideBillboardGroup (#BillboardGroup, Display);
function HideEntity (#Entity, Hide);
function HideGadget (#Gadget, State);
function HideLight (#Light, State);
function HideMenu (#Menu, State);
function HideParticleEmitter (#ParticleEmitter, Hide);
function HideWindow (#Window, State);
function Hostname ();
function Hour (Date);
function HyperLinkGadget (#Gadget, x, y, Width, Heigth, Text$, Color [, Flags]);
function ImageDepth ();
function ImageGadget (#Gadget, x, y, Width, Heigth, ImageID [, Flags]);
function ImageHeight ();
function ImageID ();
function ImageOutput ();
function ImageWidth ();
function InitCDAudio ();
function InitDatabase ();
function InitEngine3D ();
function InitJoystick ();
function InitKeyboard ();
function InitModule (#Module);
function InitMouse ();
function InitMovie ();
function InitNetwork ();
function InitPalette (#NumPaletteMax);
function InitSound ();
function InitSprite ();
function InitSprite3D ();
function Inkey ();
function Input ();
function InputRequester (Title$, Message$, DefaultString$);
function InsertElement (LinkedList());
function Int (Float);
function IPAddressField (IPAddress, Field);
function IPAddressGadget (#Gadget, x, y, Width, Heigth);
function IPString (IPAddress);
function IsFilename (Filename$);
function IsFunction (#Library, FunctionName$);
function IsFunctionEntry (#Library, EntryNumber);
function IsScreenActive ();
function JoystickAxisX ();
function JoystickAxisY ();
function JoystickButton (ButtonNumber);
function KeyboardPushed (KeyID);
function KeyboardReleased (KeyID);
function KillThread (Thread);
function LastElement (LinkedList());
function LCase (String$);
function Left (String$, Length);
function Len (String$);
function LibraryFunctionAddress ();
function LibraryFunctionName ();
function LightColor (#Light, Color);
function LightLocate (#Light, x, y, z);
function LightSpecularColor (#Light, Color);
function Line (x, y, Width, Height [, Color]);
function LineXY (x1, y1, x2, y2 [, Color]);
function ListIconGadget (#Gadget, x, y, Width, Heigth, Title$, TitleWidth [, Flags]);
function ListIndex (LinkedList());
function ListViewGadget (#Gadget, x, y, Width, Heigth [, Flags]);
function LoadFont (#Font, Name$, YSize [,Style]);
function LoadImage (#Image, FileName$);
function LoadMesh (#Mesh, Filename$);
function LoadModule (#Module, "FileName");
function LoadMovie (#Movie, FileName$);
function LoadPalette (#Palette, FileName$);
function LoadSound (#Sound, FileName$);
function LoadSprite (#Sprite, FileName$ [, Mode]);
function LoadTexture (#Texture, Filename$);
function LoadWorld (FileName$);
function Loc ();
function Locate (x, y);
function Lof ();
function Log (Value);
function Log10 (x);
function LSet (String, Length [, Character]);
function LTrim (String$);
function MakeIPAddress (Field4, Field3, Field2, Field1);
function MaterialAmbientColor (#Material, Color);
function MaterialBlendingMode (#Material, Mode);
function MaterialDiffuseColor (#Material, Color);
function MaterialFilteringMode (#Material, Mode);
function MaterialID (#Material);
function MaterialShadingMode (#Material, Mode);
function MaterialSpecularColor (#Material, Color);
function MD5FileFingerprint (Filename$);
function MD5Fingerprint (Buffer, Length);
function MemoryID ();
function MemoryStringLength (String$);
function MenuBar ();
function MenuHeight ();
function MenuID ();
function MenuItem (MenuID, Text$);
function MenuTitle (Title$);
function MeshID (#Mesh);
function MessageRequester (Title$, Text$ [, Flags]);
function Mid (String$, StartPos, Length);
function Minute (Date);
function ModuleVolume (#Module, Volume);
function Month (Date);
function MouseButton (ButtonNumber);
function MouseDeltaX ();
function MouseDeltaY ();
function MouseLocate (x, y);
function MouseWheel ();
function MouseX ();
function MouseY ();
function MoveBillboard (#Billboard, #BillboardGroup, x, y, z);
function MoveBillboardGroup (#BillboardGroup, x, y, z);
function MoveCamera (#Camera, x, y, z);
function MoveEntity (#Entity, x, y, z);
function MoveLight (#Light, x, y, z);
function MoveParticleEmitter (#ParticleEmitter, x, y, z);
function MoveWindow (x, y);
function MovieAudio (Volume, Balance);
function MovieHeight ();
function MovieInfo (Flags);
function MovieLength ();
function MovieSeek (Frame);
function MovieStatus ();
function MovieWidth ();
function NetworkClientEvent (ConnectionID);
function NetworkClientID ();
function NetworkServerEvent ();
function NewPrinterPage ();
function NextDatabaseDriver ();
function NextDatabaseRow ();
function NextDirectoryEntry ();
function NextElement (LinkedList());
function NextIPAddress ();
function NextLibraryFunction ();
function NextPackFile ();
function NextScreenMode ();
function NextSelectedFileName ();
function OffsetOf (Structure, Field);
function OnErrorExit ();
function OnErrorGosub (Addresspointer);
function OnErrorGoto (AddressPointer);
function OnErrorResume ();
function OpenComPort (#File, FileName$);
function OpenConsole ();
function OpenDatabase (#Database, ODBCDatabaseName$, User$, Password$);
function OpenDatabaseRequester (#Database);
function OpenFile (#File, FileName$);
function OpenFileRequester (Title$, DefaultFile$, Pattern$, PatternPosition [, Flags]);
function OpenGadgetList (#Gadget [, GadgetItem]);
function OpenHelp (Filename$, Topic$ [, Flags]);
function OpenLibrary (#Library, Filename$);
function OpenNetworkConnection (ServerName$, Port);
function OpenPack (Filename$);
function OpenPreferences (Filename$);
function OpenScreen (Width, Height, Depth, Title$);
function OpenSubMenu (Text$);
function OpenTreeGadgetNode (#Gadget [, Position]);
function OpenWindow (#Window, x, y, Width, Height, Flags, Title$ [, ParentID]);
function OpenWindowedScreen (WindowID(), x, y, Width, Height, AutoStretch, RightOffset, BottomOffset);
function OptionGadget (#Gadget, x, y, Width, Heigth, Text$);
function OSVersion ();
function PackerCallback (@Procedure());
function PackFileSize ();
function PackMemory (SourceMemoryID, DestinationMemoryID, SourceLength [, Level]);
function PanelGadget (#Gadget, x, y, Width, Heigth);
function ParseDate (Mask$, Date$);
function ParticleColorFader (#ParticleEmitter, RedRate, GreenRate, BlueRate);
function ParticleColorRange (#ParticleEmitter, StartColor, EndColor);
function ParticleEmissionRate (#ParticleEmitter, Rate);
function ParticleEmitterLocate (#ParticleEmitter, x, y, z);
function ParticleEmitterX (#ParticleEmitter);
function ParticleEmitterY (#ParticleEmitter);
function ParticleEmitterZ (#ParticleEmitter);
function ParticleMaterial (#ParticleEmitter, MaterialID);
function ParticleSize (#ParticleEmitter, Width, Height);
function ParticleTimeToLive (#ParticleEmitter, MininumTime, MaximumTime);
function ParticleVelocity (#ParticleEmitter, Minimum, Maximum);
function PathRequester (Title$, InitialPath$);
function PauseCDAudio ();
function PauseMovie ();
function PauseThread (Thread);
function PeekB (*MemoryBuffer);
function PeekF (*MemoryBuffer);
function PeekL (*MemoryBuffer);
function PeekS (Memory [, Length]);
function PeekW (*MemoryBuffer);
function PlayCDAudio (StartTrack, EndTrack);
function PlayModule (#Module);
function PlayMovie (#Movie, WindowID);
function PlaySound (#Sound [, Mode]);
function Plot (x, y [, Color]);
function Point (x, y);
function PokeB (*MemoryBuffer, Number);
function PokeF (*MemoryBuffer, Number.f);
function PokeL (*MemoryBuffer, Number);
function PokeS (*MemoryBuffer, Text$ [, Length]);
function PokeW (*MemoryBuffer, Number);
function Pow (Number, Exponent);
function PreferenceComment (Comment$);
function PreferenceGroup (GroupName$);
function PreviousDatabaseRow ();
function PreviousElement (LinkedList());
function Print (Text$);
function PrinterOutput ();
function PrinterPageHeight ();
function PrinterPageWidth ();
function PrintN (Text$);
function PrintRequester ();
function ProgramParameter ();
function ProgressBarGadget (#Gadget, x, y, Width, Heigth, Minimum, Maximum [, Flags]);
function Random (Maximum);
function RandomSeed (Seed);
function ReadByte ();
function ReadData (*MemoryBuffer, LengthToRead);
function ReadFile (#File, FileName$);
function ReadFloat ();
function ReadLong ();
function ReadPreferenceFloat (Keyword$, DefaultValue);
function ReadPreferenceLong (Keyword$, DefaultValue);
function ReadPreferenceString (Keyword$, DefaultValue$);
function ReadString ();
function ReadWord ();
function ReAllocateMemory (#Memory, Size);
function ReceiveNetworkData (ClientID, *DataBuffer, DataBufferLength);
function ReceiveNetworkFile (ClientID, FileName$);
function Red (Color);
function ReleaseMouse (State);
function RemoveBillboard (#Billboard, #BillboardGroup);
function RemoveGadgetItem (#Gadget, Position);
function RemoveKeyboardShortcut (#Window, Key);
function RemoveMaterialLayer (#Material);
function RemoveString (String$, RemoveString$ [, Mode]);
function RemoveSysTrayIcon (#SysTrayIcon);
function RenameFile (OldFileName$, NewFileName$);
function RenderMovieFrame (SpriteID);
function RenderWorld ();
function ReplaceString (String$, StringToFind$, StringToReplace$ [, Mode [, StartFrom]]);
function ResetList (LinkedList());
function ResizeBillboard (#Billboard, #BillboardGroup, Width, Height);
function ResizeEntity (#Entity, x, y, z);
function ResizeGadget (#Gadget, x, y, Width, Height);
function ResizeImage (#Image, Width, Height);
function ResizeMovie (x, y, Width, Height);
function ResizeParticleEmitter (#ParticleEmitter, x, y, z);
function ResizeWindow (Width, Height);
function ResumeCDAudio ();
function ResumeMovie ();
function ResumeThread (Thread);
function RGB (Red, Green, Blue);
function Right (String$, Length);
function RotateBillboardGroup (#BillboardGroup, x, y, z);
function RotateCamera (#Camera, x, y, z);
function RotateEntity (#Entity, x, y, z);
function RotateMaterial (#Material, Angle, Mode [, Layer]);
function RotateParticleEmitter (#ParticleEmitter, x, y, z);
function RotateSprite3D (#Sprite, Angle, Mode);
function Round (Number, Mode);
function RSet (String, Length [, Character]);
function RTrim (String$);
function RunProgram (ProgramName$ [, Parameter$, WorkingDirectory$ [, Flags]]);
function SaveFileRequester (Title$, DefaultFile$, Pattern$, PatternPosition);
function SaveImage (#Image, FileName$ [, Format [, Flags]]);
function SaveSprite (#Sprite, Filename$ [, ImagePlugin]);
function ScaleEntity (#Entity, x, y, z);
function ScaleMaterial (#Material, x, y [, Layer]);
function ScreenID ();
function ScreenModeDepth ();
function ScreenModeHeight ();
function ScreenModeRefreshRate ();
function ScreenModeWidth ();
function ScreenOutput ();
function ScrollAreaGadget (#Gadget, x, y, Width, Heigth, ScrollAreaWidth, ScrollAreaHeight, ScrollStep [, Flags]);
function ScrollBarGadget (#Gadget, x, y, Width, Heigth, Min, Max, PageLength [, Flags]);
function ScrollMaterial (#Material, x, y, Mode [, Layer]);
function Second (Date);
function SelectedFilePattern ();
function SelectedFontColor ();
function SelectedFontName ();
function SelectedFontSize ();
function SelectedFontStyle ();
function SelectElement (LinkedList(), Position);
function SendNetworkData (ClientID, *MemoryBuffer, Length);
function SendNetworkFile (ClientID, FileName$);
function SendNetworkString (ClientID, String$);
function SetClipboardData (DataID, Type);
function SetClipboardText (Text$);
function SetEntityAnimationTime (#Entity, Time);
function SetErrorNumber (Errornumber);
function SetFrameRate (FrameRate);
function SetGadgetFont (#Gadget, FontID());
function SetGadgetItemState (#Gadget, Position, State);
function SetGadgetItemText (#Gadget, Position, Text$, Column);
function SetGadgetState (#Gadget, State);
function SetGadgetText (#Gadget, Text$);
function SetMenuItemState (#Menu, MenuItem, State);
function SetMeshData (#Mesh, Type, Data, DataLength);
function SetModulePosition (Position);
function SetPaletteColor (Index, Color);
function SetRefreshRate (RefreshRate);
function SetWindowCallback (@ProcedureName());
function Sin (Angle);
function SizeOf (Structure);
function SkyBox (Filename$);
function SkyDome (Filename$, Curve);
function SortArray (ArrayName(), Options, [, Start, End]);
function SortList (#Font);
function SoundFrequency (#Sound, Frequency);
function SoundPan (#Sound, Pan);
function SoundVolume (#Sound, Volume);
function Space (Length);
function SpinGadget (#Gadget, x, y, Width, Heigth, Minimum, Maximum);
function SplitterGadget (#Gadget, x, y, Width, Heigth, #Gadget1, #Gadget2 [, Flags]);
function Sprite3DBlendingMode (SourceOperation, DestinationOperation);
function Sprite3DQuality (Quality);
function SpriteCollision (#Sprite1, x1, y1, #Sprite2, x2, y2);
function SpriteDepth (#Sprite);
function SpriteHeight (#Sprite);
function SpriteOutput (#Sprite);
function SpritePixelCollision (#Sprite1, x1, y1, #Sprite2, x2, y2);
function SpriteWidth (#Sprite);
function Sqr (Value);
function Start3D ();
function StartDrawing (Output);
function StartPrinting (JobName$);
function StartSpecialFX ();
function StatusBarIcon (#StatusBar, Field, ImageID);
function StatusBarText (#StatusBar, Field, Text$ [, Appearance]);
function Stop3D ();
function StopCDAudio ();
function StopDrawing ();
function StopModule ();
function StopMovie ();
function StopPrinting ();
function StopSound (#Sound);
function StopSpecialFX ();
function Str (Value);
function StrF (Value [, NbDecimals]);
function StringField (String$, Index, Separator$);
function StringGadget (#Gadget, x, y, Width, Heigth, Content$ [, Flags]);
function StrU (Value, Type);
function SysTrayIconToolTip (#SysTrayIcon, Text$);
function Tan (Angle);
function TerrainHeight (x, z);
function TextGadget (#Gadget, x, y, Width, Heigth, Text$ [, Flags]);
function TextLength (Text$);
function TextureHeight (#Texture);
function TextureID (#Texture);
function TextureOutput (#Texture);
function TextureWidth (#Texture);
function ThreadPriority (Thread, Priority);
function ToolBarImageButton (#ButtonID, ImageID);
function ToolBarSeparator ();
function ToolBarStandardButton (#ButtonID, #ButtonIcon);
function ToolBarToolTip (#ButtonID, Text$);
function TrackBarGadget (#Gadget, x, y, Width, Heigth, Minimum, Maximum [, Flags]);
function TransformSprite3D (#Sprite, x1, y1, x2, y2, x3, y3, x4, y4);
function TransparentSpriteColor (#Sprite, Red, Green, Blue);
function TreeGadget (#Gadget, x, y, Width, Heigth [, Flags]);
function TreeGadgetItemNumber (#Gadget, ItemID);
function Trim (String$);
function UCase (String$);
function UnpackMemory (SourceMemoryID, DestinationMemoryID);
function UpdateStatusBar (#StatusBar);
function UseBuffer (#Sprite);
function UseCDAudio (CDAudioDrive);
function UseDatabase (#Database);
function UseDirectory (#Directory);
function UseFile (#File);
function UseFont (#Font);
function UseGadgetList (WindowID);
function UseImage (#Image);
function UseJPEGImageDecoder ();
function UseJPEGImageEncoder ();
function UseMemory (#Memory);
function UseMovie (#Movie);
function UseOGGSoundDecoder ();
function UsePalette (#Palette);
function UsePNGImageDecoder ();
function UsePNGImageEncoder ();
function UseTGAImageDecoder ();
function UseTIFFImageDecoder ();
function UseWindow (#Window);
function Val (String$);
function ValF (String);
function WaitThread (Thread);
function WaitWindowEvent ();
function WebGadget (#Gadget, x, y, Width, Heigth, URL$ [, Flags]);
function WindowEvent ();
function WindowHeight ();
function WindowID ([ #Window]);
function WindowMouseX ();
function WindowMouseY ();
function WindowOutput ();
function WindowWidth ();
function WindowX ();
function WindowY ();
function WriteByte (Number);
function WriteData (*MemoryBuffer, LengthToWrite);
function WriteFloat (Number);
function WriteLong (Number);
function WritePreferenceFloat (Keyword$, Value);
function WritePreferenceLong (Keyword$, Value);
function WritePreferenceString (Keyword$, Value$);
function WriteString (Text$);
function WriteStringN (Text$);
function WriteWord (Number);
function Year (Date);
function ZoomSprite3D (#Sprite, Width, Height);
