#TITLE=SSB-易飞扬
#INFO
Cliptext Library for XHTML 1.0 written by ES-Computing.
This file is provided as a sample Cliptext library of EditPlus.
#SORT=n

#T=printf
printf("^!");
#T=return
return(^!);
#T=sizeof
sizeof(^!);
#T=struct
struct ^! {
     
};
#T=switch
switch (^!) {
     case :
           
           break;
}
#T=try
try {
     ^!
} catch () {
     
}
#T=while
while (^!) {
     
}
#T=公开
公开 
#T=静态
静态 
#T=类
类 
#T=启动
启动()
{

}
#T=启动类
启动类
#